const MoviesActionTypes = {
    FETCH_MOVIES_START: 'FETCH_MOVIES_START',
    FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
    FETCH_MOVIES_FAILURE: 'FETCH_MOVIES_FAILURE',
    SAVE_TITLE: 'SAVE_TITLE',
    SAVE_PAGE: 'SAVE_PAGE'
};

export default MoviesActionTypes;