const MoviesActionTypes = {
    FETCH_MOVIES_START: 'FETCH_MOVIES_START',
    FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
    FETCH_MOVIES_FAILURE: 'FETCH_MOVIES_FAILURE'
};

export default MoviesActionTypes;